### ISSUE TITLE
Problem building 

### ISSUE THREAD

**Issue by acalace** [skarppi/icloud_photo_station#10]
i am a novice user trying to install on my synology the icloud photo station
i followed the instructions and my build stops with an error - i am afraid the https site in not reachable?
i would appreciate if you could help me
thanks
Andrea

(env) admin@Cabana-HD:/var/services/homes/acalace/icloud_photo_station/spk$ sh build.sh
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/var/services/homes/admin/.wget-hsts'. HSTS will be disabled.
--2020-07-04 18:32:21-- http://raw.githubusercontent.com/SynologyOpenSource/pkgscripts-ng/master/include/pkg_util.sh
Resolving raw.githubusercontent.com... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com|151.101.0.133|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/SynologyOpenSource/pkgscripts-ng/master/include/pkg_util.sh [following]
--2020-07-04 18:32:21-- https://raw.githubusercontent.com/SynologyOpenSource/pkgscripts-ng/master/include/pkg_util.sh
Connecting to raw.githubusercontent.com|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10465 (10K) [text/plain]
Saving to: '_pkg_util.sh'

_pkg_util.sh 100%[=======================================================================================================>] 10.22K --.-KB/s in 0s

2020-07-04 18:32:22 (65.3 MB/s) - '_pkg_util.sh' saved [10465/10465]

build.sh: line 24: source: _pkg_util.sh: file not found

**Comment by Sebolains** [comment]
I had the same problem while building. The issue seems to be coming from the `source` command. I solved this problem by changing line 24 of the build.sh script in the spk directory to be:

source $PWD/_${PKG_UTIL}

Hope this helps!

**Comment by cmfrazier** [comment]
I also had this issue. @Sebolains tip corrected the issue.

**Comment by skarppi** [comment]
Thanks for the fix. It's now included in ```master``` and ```dsm6``` branches.
