### ISSUE TITLE
PyiCloudAPIResponseError 

### ISSUE THREAD

**Issue by christet2** [skarppi/icloud_photo_station#106]
## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
[NOTE]: # ( Give a BRIEF summary about your problem )
I have been using this without problem for a long time (thanks!), but for the last week or so I started to get the following error (screenshot below)

![image](https://github.com/skarppi/icloud_photo_station/assets/153562063/0264a0a9-2be8-47b8-896b-081d63ca2f76)

I don't have enough coding skills to understand what exactly the issue is...

**Comment by tonyxu-io** [comment]
Same issue here.

**Comment by Moukmouk** [comment]
I confirm the issue. Nobody found a solution?

**Comment by tonyxu-io** [comment]
I switch over to use original repo which has the fix since 1.17.0.

https://github.com/icloud-photos-downloader/icloud_photos_downloader/releases

**Comment by skarppi** [comment]
A new 0.4.0 SPK is now available with the latest icloud-photos-downloader library fixing the above issue. 

This repository doesn't anymore include sources from the original repository but just helper scripts to create SPK releases with the latest icloudpd library. It's also possible to just ssh into Synology and run ```pip install --upgrade icloudpd``` there directly in the virtualenv without installing new SPKs at all.

Note, with the icloudpd latest release requires /tmp directory to be mounted with exec flag.
sudo mount /tmp -o remount,exec

More information at https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/764.
