### ISSUE TITLE
No longer gives the choice of receiving a code (device or sms)

### ISSUE THREAD

**Issue by ADMiNZ** [skarppi/icloud_photo_station#107]
When connecting, there is no choice of how to receive the code. Just receive the code on your device. But you need it via SMS.

**Comment by ADMiNZ** [comment]
The mechanism has been fixed https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/803

**Comment by ADMiNZ** [comment]
Hello @skarppi, Can you update?

**Comment by skarppi** [comment]
New release now available:
https://github.com/skarppi/icloud_photo_station/releases/tag/v1.23.4
