### ISSUE TITLE
Python on Synology DSM7

### ISSUE THREAD

**Issue by BLLiNNK** [skarppi/icloud_photo_station#13]
Hi 

following update to Synology DSM7 which Python 3 built in I'm getting the below error.

-sh: /volume1/homes/<user>/env/bin/icloudpd: /volume1/homes/<user>/env/bin/python3: bad interpreter: No such file or directory

Any help would be greatly appreciated

**Comment by skarppi** [comment]
I had the same issue after DSM7 upgrade. There is now 0.3.0 release which should work with DSM7.
