### ISSUE TITLE
Keychain with DSM 7.x

### ISSUE THREAD

**Issue by BLLiNNK** [skarppi/icloud_photo_station#20]
## Summary
Sorry for another question but can't seem to work out how to use the system keychain to store password with the new build for DSM 7.x. Any assistance would be appreciated.

## Context
Using icloud_photo_station-0.3.0.spk for DSM 7.x using task scheduler

**Comment by skarppi** [comment]
The [keyring library ](https://keyring.readthedocs.io) used by pyiCloud supports multiple backends but I'm not really sure if any of them is available for Synology DSM.
