### ISSUE TITLE
iOS 11 - Photos in HEIC Format

### ISSUE THREAD

**Issue by cutzenfriend** [skarppi/icloud_photo_station#5]
Hi, since iOS 11 Photos are save as HEIC Format in iCloud and also downloaded as such.

![ios11-heic](https://user-images.githubusercontent.com/1510611/30543047-e32cff8e-9c81-11e7-8152-a80a0a119705.png)

This is completly useless for windows / linux... Maybe convert themautomatically to jpg could be a solution?

I also opened this issue on the original repo...

**Comment by skarppi** [comment]
Original repo has some ideas: https://github.com/ndbroadbent/icloud_photos_downloader/issues/108
